server:
  port: 8081

mybatis-plus:
  　　typeAliasesPackage: com.vue.demo.entity
  　　mapperLocations: classpath:mapper/*.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: yang156122
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    #redis单机配置
    host: localhost
    port: 6379
    # 选择redis的数据库的分库
    database: 5
    #redis连接池配置
    jedis:
      pool:
        max-idle: 10
        min-idle: 5
        max-active: 100
        max-wait: 3000
        timeout: 6005
  data:
    mongodb:
      uri: mongodb://localhost:27017/userArticle

